providers:
  docker:
    swarmMode: true
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-public

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

api:
  dashboard: true

accessLog: {}
log:
  level: DEBUG

certificatesResolvers:
  le:
    acme:
      email: coder2000@gmail.com
      storage: /certificates/acme.json
      tlsChallenge: {}
